from typing import Any, Dict

TOOL_SCHEMAS_EXTENDED: Dict[str, Dict[str, Any]] = {'delegate_task': {'best_practices': ['Use for independent, well-defined subtasks',
                                      'Provide sufficient context for the sub-agent'],
                   'description': 'Delegate a sub-task to a specialized agent. Use for complex, '
                                  'self-contained subtasks.',
                   'example': '{"action": "delegate_task", "args": {"task": "Write unit tests for '
                              'UserService", "context": "UserService is in src/services/user.py"}}',
                   'name': 'delegate_task',
                   'parameters': {'context': {'description': 'Relevant context from the main task',
                                              'required': False,
                                              'type': 'string'},
                                  'task': {'description': 'Clear description of the subtask',
                                           'required': True,
                                           'type': 'string'}},
                   'returns': 'Sub-agent completion result'},
 'generate_image': {'best_practices': ['Be specific and detailed in your prompt for better results',
                                       'Use save_to_project to add generated images to the '
                                       'codebase',
                                       'Generated images are saved to assets/images/ by default'],
                    'description': 'Generate an AI image from a text prompt. The image is created '
                                   "by Gemini's image generation model.",
                    'example': '{"action": "generate_image", "args": {"prompt": "A minimalist logo '
                               'for a coffee shop", "save_to_project": true, "filename": '
                               '"logo.png"}}',
                    'name': 'generate_image',
                    'parameters': {'filename': {'description': 'Custom filename for saved image '
                                                               '(without path)',
                                                'required': False,
                                                'type': 'string'},
                                   'prompt': {'description': 'Detailed description of the image to '
                                                             'generate',
                                              'required': True,
                                              'type': 'string'},
                                   'save_to_project': {'default': False,
                                                       'description': 'Whether to save the '
                                                                      'generated image to the '
                                                                      "project's assets folder",
                                                       'required': False,
                                                       'type': 'boolean'}},
                    'returns': 'Image generation request message. The generated image will appear '
                               'in the response.'},
 'git_branches': {'best_practices': ['Check existing branches before creating new ones'],
                  'description': 'List all local and remote branches.',
                  'example': '{"action": "git_branches", "args": {}}',
                  'name': 'git_branches',
                  'parameters': {},
                  'returns': 'Branch list with current branch marked'},
 'git_checkout': {'best_practices': ['Use descriptive branch names (feature/, fix/, refactor/)',
                                     'Commit or stash changes before switching'],
                  'description': 'Switch to a branch or create a new one.',
                  'example': '{"action": "git_checkout", "args": {"branch": "feature/new-api", '
                             '"create": true}}',
                  'name': 'git_checkout',
                  'parameters': {'branch': {'description': 'Branch name',
                                            'required': True,
                                            'type': 'string'},
                                 'create': {'default': False,
                                            'description': 'Create new branch if true',
                                            'required': False,
                                            'type': 'boolean'}},
                  'returns': 'Checkout confirmation'},
 'git_clone': {'best_practices': ['Use HTTPS for public repos',
                                  "Ensure target directory is empty or doesn't exist"],
               'description': 'Clone a repository from a URL.',
               'example': '{"action": "git_clone", "args": {"url": '
                          '"https://github.com/user/repo.git", "path": "my-project"}}',
               'name': 'git_clone',
               'parameters': {'path': {'default': '.',
                                       'description': 'Target directory',
                                       'required': False,
                                       'type': 'string'},
                              'url': {'description': 'Repository URL (HTTPS or SSH)',
                                      'required': True,
                                      'type': 'string'}},
               'returns': 'Clone result'},
 'git_commit': {'best_practices': ['Use conventional commit format (type: description)',
                                   'Make atomic commits (one logical change)',
                                   'Verify changes with git_status first'],
                'description': 'Stage all changes and create a commit.',
                'example': '{"action": "git_commit", "args": {"message": "feat: add user '
                           'authentication module"}}',
                'name': 'git_commit',
                'parameters': {'message': {'description': 'Commit message (follow conventional '
                                                          'commits)',
                                           'required': True,
                                           'type': 'string'}},
                'returns': 'Commit confirmation or error'},
 'git_init': {'best_practices': ['Add .gitignore after initialization', 'Make an initial commit'],
              'description': 'Initialize a new git repository in the workspace.',
              'example': '{"action": "git_init", "args": {}}',
              'name': 'git_init',
              'parameters': {},
              'returns': 'Init confirmation'},
 'git_log': {'best_practices': ['Review recent commits to understand context'],
             'description': 'View commit history.',
             'example': '{"action": "git_log", "args": {"limit": 5}}',
             'name': 'git_log',
             'parameters': {'limit': {'default': 10,
                                      'description': 'Number of commits to show',
                                      'required': False,
                                      'type': 'integer'}},
             'returns': 'Commit history with hashes, authors, dates, messages'},
 'git_pull': {'best_practices': ['Pull before starting new work', 'Resolve conflicts carefully'],
              'description': 'Pull latest changes from remote repository.',
              'example': '{"action": "git_pull", "args": {}}',
              'name': 'git_pull',
              'parameters': {'branch': {'description': 'Branch to pull',
                                        'required': False,
                                        'type': 'string'},
                             'remote': {'default': 'origin',
                                        'description': 'Remote name',
                                        'required': False,
                                        'type': 'string'}},
              'returns': 'Pull result showing changes'},
 'git_push': {'best_practices': ['Ensure all tests pass before pushing',
                                 'Create feature branches for new work'],
              'description': 'Push local commits to remote repository.',
              'example': '{"action": "git_push", "args": {"remote": "origin", "branch": '
                         '"feature/auth"}}',
              'name': 'git_push',
              'parameters': {'branch': {'description': 'Branch to push (default: current)',
                                        'required': False,
                                        'type': 'string'},
                             'remote': {'default': 'origin',
                                        'description': 'Remote name',
                                        'required': False,
                                        'type': 'string'}},
              'returns': 'Push result or error'},
 'git_status': {'best_practices': ['Check before and after making changes',
                                   'Verify what will be committed'],
                'description': 'Check current git repository status (changes, branch, etc.).',
                'example': '{"action": "git_status", "args": {}}',
                'name': 'git_status',
                'parameters': {},
                'returns': 'Git status output showing staged/unstaged changes'},
 'save_generated_images': {'best_practices': ['Use after generating multiple images to save all at '
                                              'once',
                                              'Organize with subdirectories for different '
                                              'purposes'],
                           'description': "Save all recently generated images to the project's "
                                          'assets folder.',
                           'example': '{"action": "save_generated_images", "args": {"subdir": '
                                      '"generated"}}',
                           'name': 'save_generated_images',
                           'parameters': {'subdir': {'description': 'Subdirectory within '
                                                                    'assets/images',
                                                     'required': False,
                                                     'type': 'string'}},
                           'returns': 'List of saved image paths'},
 'save_image': {'best_practices': ['Use to save AI-generated images or web images to the project',
                                   'Specify meaningful filenames for organization'],
                'description': "Download and save an image from a URL to the project's assets "
                               'folder.',
                'example': '{"action": "save_image", "args": {"url": '
                           '"https://example.com/image.png", "filename": "hero.png"}}',
                'name': 'save_image',
                'parameters': {'filename': {'description': 'Custom filename (auto-generated if not '
                                                           'provided)',
                                            'required': False,
                                            'type': 'string'},
                               'subdir': {'description': 'Subdirectory within assets/images',
                                          'required': False,
                                          'type': 'string'},
                               'url': {'description': 'Image URL to download',
                                       'required': True,
                                       'type': 'string'}},
                'returns': 'Path where image was saved, or error message'},
 'self_check': {'best_practices': ['Use when tool behavior seems inconsistent or environment '
                                   'issues are suspected',
                                   'Run before long or complex tasks to catch missing '
                                   'dependencies'],
                'description': 'Run a global health check for tools and environment (workspace, '
                               'git, web, commands).',
                'example': '{"action": "self_check", "args": {}}',
                'name': 'self_check',
                'parameters': {},
                'returns': 'Structured diagnostics for workspace, git, commands, and web '
                           'dependencies'},
 'web_browse': {'best_practices': ['Use to read documentation pages',
                                   'Follow up on web_search results'],
                'description': 'Browse a specific URL and extract text content.',
                'example': '{"action": "web_browse", "args": {"url": '
                           '"https://docs.python.org/3/library/asyncio.html"}}',
                'name': 'web_browse',
                'parameters': {'url': {'description': 'Full URL to browse',
                                       'required': True,
                                       'type': 'string'}},
                'returns': 'Page text content (capped at 10k chars)'},
 'web_search': {'best_practices': ['Use for documentation, error solutions, best practices',
                                   'Be specific in queries for better results'],
                'description': 'Search the web for information using DuckDuckGo.',
                'example': '{"action": "web_search", "args": {"query": "python asyncio best '
                           'practices 2025"}}',
                'name': 'web_search',
                'parameters': {'query': {'description': 'Search query',
                                         'required': True,
                                         'type': 'string'}},
                'returns': 'Top search results with titles, links, and snippets'}}
