from typing import Any, Dict

TOOL_SCHEMAS_PRIMARY: Dict[str, Dict[str, Any]] = {'activate_skill': {'best_practices': ['Activate skills before starting complex framework-specific '
                                       'tasks',
                                       "Follow the skill's instructions strictly once loaded"],
                    'description': 'Load a specific file-based skill (SKILL.md) to adopt expert '
                                   'behaviors for a particular framework or workflow.',
                    'example': '{"action": "activate_skill", "args": {"skill_name": '
                               '"react-refactoring"}}',
                    'name': 'activate_skill',
                    'parameters': {'skill_name': {'description': 'Name of the skill to activate '
                                                                 "(e.g., 'react-refactoring', "
                                                                 "'fastapi-auth')",
                                                  'required': True,
                                                  'type': 'string'}},
                    'returns': 'The rules and workflows defined in the skill file'},
 'apply_patch': {'best_practices': ['Ensure diff format is correct (use --- a/ and +++ b/ '
                                    'prefixes)',
                                    'Context lines help ensure correct placement'],
                 'description': 'Apply a unified diff patch to modify files. Useful for complex '
                                'multi-file changes.',
                 'example': '{"action": "apply_patch", "args": {"patch": "--- a/file.py\\n+++ '
                            'b/file.py\\n@@ -1,3 +1,3 @@\\n-old line\\n+new line"}}',
                 'name': 'apply_patch',
                 'parameters': {'patch': {'description': 'Unified diff format patch content',
                                          'required': True,
                                          'type': 'string'}},
                 'returns': 'Success message or detailed error'},
 'delete_path': {'best_practices': ['Double-check path before deleting',
                                    'Consider git status before deleting tracked files'],
                 'description': 'Permanently delete a file or directory. Use with caution.',
                 'example': '{"action": "delete_path", "args": {"path": "temp/old_file.txt"}}',
                 'name': 'delete_path',
                 'parameters': {'path': {'description': 'Path to delete',
                                         'required': True,
                                         'type': 'string'}},
                 'returns': 'Success confirmation or error'},
 'get_dependencies': {'best_practices': ['Run early to understand project tech stack',
                                         'Use to check for version conflicts'],
                      'description': 'Analyze project dependencies from package files '
                                     '(package.json, requirements.txt, etc.).',
                      'example': '{"action": "get_dependencies", "args": {}}',
                      'name': 'get_dependencies',
                      'parameters': {},
                      'returns': 'Contents of all found dependency files'},
 'get_file_tree': {'best_practices': ['Use early in task to understand codebase',
                                      'Increase max_depth for deeper exploration'],
                   'description': 'Get a recursive tree view of directory structure. Excellent for '
                                  'project overview.',
                   'example': '{"action": "get_file_tree", "args": {"path": ".", "max_depth": 3}}',
                   'name': 'get_file_tree',
                   'parameters': {'max_depth': {'default': 2,
                                                'description': 'Maximum recursion depth',
                                                'required': False,
                                                'type': 'integer'},
                                  'path': {'default': '.',
                                           'description': 'Root path for the tree',
                                           'required': False,
                                           'type': 'string'}},
                   'returns': 'ASCII tree representation of directory structure'},
 'get_symbol_info': {'best_practices': ['Use to understand code before modifying',
                                        'Check usages before renaming'],
                     'description': 'Find where a symbol (function, class, variable) is defined.',
                     'example': '{"action": "get_symbol_info", "args": {"symbol_name": '
                                '"UserService"}}',
                     'name': 'get_symbol_info',
                     'parameters': {'symbol_name': {'description': 'Name of the symbol to find',
                                                    'required': True,
                                                    'type': 'string'}},
                     'returns': 'Definition locations found via grep'},
 'grep_search': {'best_practices': ['Use to find function/class definitions',
                                    'Use to trace imports and dependencies',
                                    'Limit with extensions for large codebases'],
                 'description': 'Search for text content inside files. Case-insensitive. Essential '
                                'for finding code references.',
                 'example': '{"action": "grep_search", "args": {"query": "def calculate", '
                            '"extensions": [".py"]}}',
                 'name': 'grep_search',
                 'parameters': {'extensions': {'description': 'Filter by file extensions (e.g., '
                                                              "['.py', '.js'])",
                                               'required': False,
                                               'type': 'array[string]'},
                                'path': {'default': '.',
                                         'description': 'Starting directory',
                                         'required': False,
                                         'type': 'string'},
                                'query': {'description': 'Text or pattern to search for',
                                          'required': True,
                                          'type': 'string'}},
                 'returns': 'Matching lines with file:line format (capped at 50)'},
 'list_dir': {'best_practices': ['Use to explore project structure',
                                 'Start with root to understand project layout'],
              'description': 'List files and directories in a path. Shows icons for type '
                             'distinction.',
              'example': '{"action": "list_dir", "args": {"path": "src"}}',
              'name': 'list_dir',
              'parameters': {'path': {'default': '.',
                                      'description': 'Directory path to list (default: current)',
                                      'required': False,
                                      'type': 'string'}},
              'returns': 'Formatted list with 📁 for dirs and 📄 for files'},
 'patch_file': {'best_practices': ['CRITICAL: Target must match EXACTLY, including indentation',
                                   'Read the file first to get the exact text',
                                   'Use for small, focused changes',
                                   'For large changes, prefer write_file'],
                'description': 'Surgically replace a specific block of text in a file. Most '
                               'efficient for targeted edits.',
                'example': '{"action": "patch_file", "args": {"path": "main.py", "target": "def '
                           'old_func():", "replacement": "def new_func():"}}',
                'name': 'patch_file',
                'parameters': {'path': {'description': 'Path to the file to patch',
                                        'required': True,
                                        'type': 'string'},
                               'replacement': {'description': 'New text to replace the target with',
                                               'required': True,
                                               'type': 'string'},
                               'target': {'description': 'EXACT text to find and replace '
                                                         '(including whitespace)',
                                          'required': True,
                                          'type': 'string'}},
                'returns': 'Success message or error if target not found'},
 'read_file': {'best_practices': ['Always read a file before attempting to modify it',
                                  'Check file existence before reading'],
               'description': 'Read the contents of a single file. Use for understanding existing '
                              'code before modifications.',
               'example': '{"action": "read_file", "args": {"path": "src/utils/helpers.py"}}',
               'name': 'read_file',
               'parameters': {'path': {'description': 'Relative or absolute path to the file',
                                       'required': True,
                                       'type': 'string'}},
               'returns': 'File contents wrapped in code blocks, or error message'},
 'read_files': {'best_practices': ['Use when you need to understand relationships between files',
                                   'Limit to 5-10 files to avoid context overflow'],
                'description': 'Read multiple files in a single operation. Efficient for '
                               'understanding related code.',
                'example': '{"action": "read_files", "args": {"paths": ["src/index.js", '
                           '"src/app.js"]}}',
                'name': 'read_files',
                'parameters': {'max_bytes': {'default': 200000,
                                             'description': 'Maximum bytes per file (truncates if '
                                                            'exceeded)',
                                             'required': False,
                                             'type': 'integer'},
                               'paths': {'description': 'List of file paths to read',
                                         'required': True,
                                         'type': 'array[string]'}},
                'returns': 'Contents of all files, each wrapped in code blocks'},
 'run_command': {'best_practices': ['Use for verification (tests, linting, type checking)',
                                    'Check exit codes for success/failure',
                                    'Break long pipelines into separate commands for clarity'],
                 'description': 'Execute a shell command. Use for running tests, builds, '
                                'installations, and any CLI operation.',
                 'example': '{"action": "run_command", "args": {"command": "npm test"}}',
                 'name': 'run_command',
                 'parameters': {'command': {'description': 'Shell command to execute',
                                            'required': True,
                                            'type': 'string'},
                                'cwd': {'description': 'Working directory for the command',
                                        'required': False,
                                        'type': 'string'}},
                 'returns': 'Command output with exit status',
                 'security_note': 'Commands run with user privileges. Avoid dangerous operations.'},
 'search_files': {'best_practices': ['Use specific patterns to limit results',
                                     'Combine with read_file to examine matches'],
                  'description': 'Search for files matching a glob pattern. Finds files by name.',
                  'example': '{"action": "search_files", "args": {"pattern": "*.test.js", "path": '
                             '"src"}}',
                  'name': 'search_files',
                  'parameters': {'path': {'default': '.',
                                          'description': 'Starting directory for search',
                                          'required': False,
                                          'type': 'string'},
                                 'pattern': {'description': "Glob pattern (e.g., '*.py', "
                                                            "'test_*.js')",
                                             'required': True,
                                             'type': 'string'}},
                  'returns': 'List of matching file paths (capped at 50)'},
 'spawn_subagent': {'best_practices': ['Use to delegate complex, isolated tasks',
                                       'Provide very clear scope and expected output format'],
                    'description': 'Spawn a specialized sub-agent with specific instructions to '
                                   'handle a focused task autonomously.',
                    'example': '{"action": "spawn_subagent", "args": {"agent_type": "researcher", '
                               '"task": "Read the Stripe API docs on webhooks and write a '
                               'summary."}}',
                    'name': 'spawn_subagent',
                    'parameters': {'agent_type': {'description': 'Type of agent (e.g., '
                                                                 "'researcher', 'developer', "
                                                                 "'reviewer', 'testing', "
                                                                 "'documentation')",
                                                  'required': True,
                                                  'type': 'string'},
                                   'task': {'description': 'Detailed instructions and scope for '
                                                           'the sub-agent',
                                            'required': True,
                                            'type': 'string'}},
                    'returns': "The final summary and artifacts from the sub-agent's execution"},
 'write_file': {'best_practices': ['Include complete, production-ready code',
                                   'Add appropriate imports and type hints',
                                   'Follow project conventions for formatting'],
                'description': 'Create a new file or completely overwrite an existing file. '
                               'Creates parent directories automatically.',
                'example': '{"action": "write_file", "args": {"path": "src/new_module.py", '
                           '"content": "def hello():\\n    return \\"Hello, World!\\""}}',
                'name': 'write_file',
                'parameters': {'content': {'description': 'Complete file contents to write',
                                           'required': True,
                                           'type': 'string'},
                               'path': {'description': 'Path where the file will be written',
                                        'required': True,
                                        'type': 'string'}},
                'returns': 'Success message with character count, or error'},
 'write_files': {'best_practices': ['Use for creating related files together (e.g., module + '
                                    'tests)',
                                    'Ensure all files are syntactically valid'],
                 'description': 'Write multiple files in a single operation. Atomic and efficient.',
                 'example': '{"action": "write_files", "args": {"files": [{"path": "a.py", '
                            '"content": "# File A"}, {"path": "b.py", "content": "# File B"}]}}',
                 'name': 'write_files',
                 'parameters': {'files': {'description': 'List of file objects with path and '
                                                         'content',
                                          'required': True,
                                          'type': 'array[{path: string, content: string}]'}},
                 'returns': 'Status for each file written'}}
